# store employee
# POST http://127.0.0.1:8080/api/employees HTTP/1.1 Content-Type: application/json Accept: application/json

# {
#     "name": "Maaz",
#     "email": "maazktk588@gmail.com",
#     "phone_no": "12312",
#     "gender" : "male",
#     "age" : "24"
# }


# listing of employees
# GET http://127.0.0.1:8000/api/employees HTTP/1.1 Content-Type: application/json Accept: application/json

# get single employee
# GET http://127.0.0.1:8000/api/employees/2 HTTP/1.1 Content-Type: application/json Accept: application/json

# delete an employee
GET http://127.0.0.1:8000/api/employees/2 HTTP/1.1 Content-Type: application/json Accept: application/json
